package azuredb

func dbInitQuery() string {
	return `
	CREATE TABLE IF NOT EXISTS schedules (
		ID TEXT NOT NULL,
		CIRCLE TEXT NOT NULL,
		TITLE TEXT NOT NULL,
		DESCRIPTION TEXT,
		DATE TEXT NOT NULL,
		START TEXT NOT NULL,
		END TEXT NOT NULL,
		OFFLINE INT NOT NULL DEFAULT 0,
		CREATED TEXT NOT NULL,
		UPDATED TEXT NOT NULL,
		DELETED INT NOT NULL DEFAULT 0
	)`
}
